### ISSUE TITLE
Handling of negative spec_step and spec_linewidth

### ISSUE THREAD

**Issue by patrick-austin** [muon-spectroscopy-computational-project/mudirac#15]
**Describe the bug**
Submitting a negative spec_step results in the command never completing.
Submitting a negative spec_linewidth results in a completing job, but don't think that a negative width is physically valid.

**To Reproduce**
```yaml
element: Au
isotope: -1
xr_lines: K1:L3-K1:L3
uehling_correction: false
nuclear_model: POINT
output: 1
write_spec: true
spec_step: -10000.0
spec_linewidth: 100000.0
```
```yaml
element: Au
isotope: -1
xr_lines: K1:L3-K1:L3
uehling_correction: false
nuclear_model: POINT
output: 1
write_spec: true
spec_step: 10000.0
spec_linewidth: -100000.0
```

**Expected behavior**
The former should definitely not be allowed. A validation error should prevent a negative step being used to prevent the command never completing.
I also don't think that a negative linewidth is physically valid, but this is less of an issue as it doesn't cause a total failure like the step does.

**Screenshots**
Spectrum with 1e5 linewidth
![image](https://github.com/muon-spectroscopy-computational-project/mudirac/assets/61705287/ba8554aa-f3fd-4217-9dde-a981ba1bc505)

Spectrum with -1e5 linewidth
![image](https://github.com/muon-spectroscopy-computational-project/mudirac/assets/61705287/3ffb1d27-57a5-4a24-88b8-83ce3f67a41e)

**~Desktop~VM (please complete the following information):**
 - OS: Rocky
 - Version 8
